let a=5.5;
x=Math.round(a);//round figer krdega
//console.log(x);
y=Math.ceil(a);//up side number pr round figer
//console.log(y);
z=Math.floor(a);//down side number pr round figer
//console.log(z);
b=Math.trunc(a);//point k number hi gayab kr dega
//console.log(b);
//console.log(Math.pow(2,2));//secound number jitna bhii haiii utni baar multiply hoga
//console.log(Math.sqrt(7));//squar root

let m=10.54;
o=Math.round(m);
console.log(o);
n=Math.ceil(m);
console.log(n);
r=Math.floor(m);
console.log(r);
i=Math.trunc(m);
console.log(i);
console.log(Math.pow(1,5));
console.log(Math.sqrt(10));